// Code generated by MockGen. DO NOT EDIT.
// Source: books_handler.go

// Package books is a generated GoMock package.
package books

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	books "github.com/yeremiaaryo/gotu-assignment/internal/model/books"
)

// MockbooksUsecase is a mock of booksUsecase interface.
type MockbooksUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockbooksUsecaseMockRecorder
}

// MockbooksUsecaseMockRecorder is the mock recorder for MockbooksUsecase.
type MockbooksUsecaseMockRecorder struct {
	mock *MockbooksUsecase
}

// NewMockbooksUsecase creates a new mock instance.
func NewMockbooksUsecase(ctrl *gomock.Controller) *MockbooksUsecase {
	mock := &MockbooksUsecase{ctrl: ctrl}
	mock.recorder = &MockbooksUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockbooksUsecase) EXPECT() *MockbooksUsecaseMockRecorder {
	return m.recorder
}

// GetBooks mocks base method.
func (m *MockbooksUsecase) GetBooks(ctx context.Context, search string, pageSize, pageIndex int) ([]books.Model, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBooks", ctx, search, pageSize, pageIndex)
	ret0, _ := ret[0].([]books.Model)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBooks indicates an expected call of GetBooks.
func (mr *MockbooksUsecaseMockRecorder) GetBooks(ctx, search, pageSize, pageIndex interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBooks", reflect.TypeOf((*MockbooksUsecase)(nil).GetBooks), ctx, search, pageSize, pageIndex)
}
