version: '3'

services:
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
    restart: always
    container_name: gotu_redis
  db:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - docker-be_default
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gotu
      - POSTGRES_ENCODING=UTF8
      - POSTGRES_COLLATE=C
      - POSTGRES_COLLATE_TYPE=C
    container_name: gotu-postgres
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:
  redis_data:
  mongo_data:
  postgresql:
  postgresql_data:

networks:
  docker-be_default: